services:
  db:
    image: neondatabase/neon_local:latest
    container_name: tarot-card-game-db
    ports:
      - "5432:5432"
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      NEON_BRANCH_ID: ${NEON_BRANCH_ID}
    # Optional: Persist a Neon branch per Git branch and across restarts
    # See: https://neon.com/docs/local/neon-local
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consistent
