version: '3'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - npm install --ignore-scripts
  build:
    desc: Build all packages
    cmds:
      - npm run build
  test:
    desc: Run tests
    cmds:
      - npm test
  web:dev:
    desc: Run web dev server
    cmds:
      - npm run dev:web
  web:e2e:
    desc: Run Playwright tests (dev server must be running)
    cmds:
      - npm run e2e:web
  web:seed:deck:
    desc: Seed a demo deck via API
    cmds:
      - curl -s -X POST http://localhost:3000/api/admin/seed-deck || true
  web:seed:cards:
    desc: Seed demo cards via API
    cmds:
      - curl -s -X POST http://localhost:3000/api/admin/seed-cards || true
  web:reset:
    desc: Reset in-memory DB via API
    cmds:
      - curl -s -X POST http://localhost:3000/api/admin/reset-db || true
  ws:dev:
    desc: Run WebSocket stub server (ws://localhost:8787)
    cmds:
      - node packages/ws-stub/dist/index.js
